### ISSUE TITLE
Not execute the  while loop in computeStepLengthMT()? 

### ISSUE THREAD

**Issue by narutojxl** [koide3/ndt_omp#13]
Hi @koide3 , thanks for you sharing the work. When calculating the step in [computeStepLengthMT()]( https://github.com/koide3/ndt_omp/blob/master/include/pclomp/ndt_omp_impl.hpp#L834) func,   `bool interval_converged = (step_max - step_min) > 0`,  `step_max = step_size_, step_min 
 = transformation_epsilon_ / 2,` `step_size_ = 0.1,`  `transformation_epsilon_ = 0.1,` so the `interval_converged = true`,  Do we need initialize  `interval_converged = false` before we  start calculate the optimal step of delta_p_norm?

Best
jxl

**Comment by koide3** [comment]
Hi @narutojxl ,
Probably, yes, we should set interval_converged to false... It could be a bug in the original PCL implementation. Did you see a difference when you fix this?
