### ISSUE TITLE
usage of calculateScore ?

### ISSUE THREAD

**Issue by MikeZhu92** [koide3/ndt_omp#16]
Thank you for creating this great project.

I've a question regarding to the last function in the source code `calculateScore`.

Is this a new way to evaluate the ndt matching result ?

**Comment by koide3** [comment]
Hi @MikeZhu92,

```calculateScore()``` computes the negative log likelihood that is what the NDT minimizes. See (6.10) in [this thesis](http://www.diva-portal.org/smash/get/diva2:276162/FULLTEXT02.pdf).

**Comment by MikeZhu92** [comment]
> Hi @MikeZhu92,
> 
> `calculateScore()` computes the negative log likelihood that is what the NDT minimizes. See (6.10) in [this thesis](http://www.diva-portal.org/smash/get/diva2:276162/FULLTEXT02.pdf).

Thank you for your help!
