### ISSUE TITLE
How to set num_threads?

### ISSUE THREAD

**Issue by FishInWave** [koide3/ndt_omp#17]
hi, @koide3 
In hdl_graph_slam project, I find follow code:
`if(num_threads>0)`{ndt->setNumThreads(num_threads)}
I note that the value of "ndt_num_threads" is always set to 0, so when I wanted to use NDT_OMP in my 8 core CPU, I should set NumThreads = 0?

**Comment by koide3** [comment]
Hi @FishInWave ,
By default (if num_threads == 0), NDT_OMP uses all the CPU cores. So, usually, you don't need to specify the number of cores to be used unless you want to leave some cores for other purposes.

https://github.com/koide3/ndt_omp/blob/c799f459b4838dd9c65968573370b16c4e7ce7d9/include/pclomp/ndt_omp_impl.hpp#L75

**Comment by FishInWave** [comment]
> Hi @FishInWave ,
> By default (if num_threads == 0), NDT_OMP uses all the CPU cores. So, usually, you don't need to specify the number of cores to be used unless you want to leave some cores for other purposes.
> 
> https://github.com/koide3/ndt_omp/blob/c799f459b4838dd9c65968573370b16c4e7ce7d9/include/pclomp/ndt_omp_impl.hpp#L75

Thank you for your explaination！
