### ISSUE TITLE
cmake error with tx2(arm)

### ISSUE THREAD

**Issue by autoperson** [koide3/ndt_omp#2]
c++: error: unrecognized command line option ‘-msse’
c++: error: unrecognized command line option ‘-msse2’
c++: error: unrecognized command line option ‘-msse3’
c++: error: unrecognized command line option ‘-msse4’
c++: error: unrecognized command line option ‘-msse4.1’
c++: error: unrecognized command line option ‘-msse4.2’
c++: error: unrecognized command line option ‘-msse’
c++: error: unrecognized command line option ‘-msse2’
c++: error: unrecognized command line option ‘-msse3’
c++: error: unrecognized command line option ‘-msse4’
c++: error: unrecognized command line option ‘-msse4.1’
c++: error: unrecognized command line option ‘-msse4.2’
ndt_omp/CMakeFiles/ndt_omp.dir/build.make:62: recipe for target 'slam/ndt_omp/CMakeFiles/ndt_omp.dir/src/pclomp/voxel_grid_covariance_omp.cpp.o' failed
make[2]: *** [slam/ndt_omp/CMakeFiles/ndt_omp.dir/src/pclomp/voxel_grid_covariance_omp.cpp.o] Error 1

I modify CMakeLists.txt with:
add_definitions(-std=c++11)
set(CMAKE_CXX_FLAGS "-std=c++11")
still have error:
catkin_ws/src/slam/ndt_omp/include/pclomp/gicp_omp_impl.hpp:78:61: error: ‘omp_get_thread_num’ was not declared in this scope
     auto& nn_indecies = nn_indecies_array[omp_get_thread_num()];

**Comment by koide3** [comment]
It seems it failed to find OpenMP. Can you check if OpenMP has been installed in your environment?

**Comment by autoperson** [comment]
I  slove this problem. OpenMP has been installed ,but need to modify CMAKE_CXX_FLAGS "-std=c++11 -fopenmp" in cmakelist.
