### ISSUE TITLE
How to tune parameters in gicp_omp

### ISSUE THREAD

**Issue by meyrin15** [koide3/ndt_omp#21]
Thanks for the great work!!

I'm slamming on kitti with gicp_omp but it doesn't work well.
How do I tune the parameters?
The program is run in ros and ubuntu 20.04 and the data is played back at 0.2 times the speed. 
And 3.5m voxel grid is used for source and target clouds.
I also use a minmax filter of 1-150m.
(By the way, I can't use gpu.)

gicp params
MaxCorrespondenceDistance : 3.0
TransformationEpsilon : 1e-8

The following uses data from kitti00.

scan2scan

![スクリーンショット 2020-06-30 21-48-58](https://user-images.githubusercontent.com/66852766/86128255-1e4c0b80-bb1c-11ea-904c-34cccda7fb80.png)
Green :ground truth, yellow : gicp_omp

scan2accumatedscan(n=30)(Using the last n scans for target)

![スクリーンショット 2020-06-30 21-54-14](https://user-images.githubusercontent.com/66852766/86128389-450a4200-bb1c-11ea-9c9c-6067ede54257.png)

Thank you for reading.

**Comment by koide3** [comment]
Hi @meyrin15 ,
You can give [our new GICP implementation](https://github.com/SMRT-AIST/fast_gicp) a try that is more accurate and faster than one in this package. We obtained the following trajectory with frame-by-frame registration. 

Used parameters
- ApproxVoxelGrid: 0.25m
- CorrespondenceRandomness: 20
- MaxCorrespondenceDistance: 1.0

![gicp](https://user-images.githubusercontent.com/31344317/86192099-b4ffe300-bb83-11ea-97ef-ebaddfe595d9.png)

**Comment by meyrin15** [comment]
Thank you for publishing the sample code!
When I ran it, the FPS was slow and my PC seemed to be poor.
In your sample I was able to draw a trajectory on my PC.

![スクリーンショット 2020-07-01 15-25-48](https://user-images.githubusercontent.com/66852766/86210223-328d1880-bbaf-11ea-95d9-f6605e6cc0ff.png)
