### ISSUE TITLE
ndt_omp_impl.hpp seems always be converged ?? delta_p_norm can be zero ??

### ISSUE THREAD

**Issue by kyo055** [koide3/ndt_omp#23]
The code in ndt_omp_impl.hpp 134～139； How does it work ?
```
    if (delta_p_norm == 0 || delta_p_norm != delta_p_norm)
    {
      trans_probability_ = score / static_cast<double> (input_->points.size ());
      converged_ = delta_p_norm == delta_p_norm;
      return;
    }
```

**Comment by koide3** [comment]
It checks if ```delta_p_norm``` is NaN. It's really tricky, and I thinks it should be modified with ```std::isnan``` for better readability.

**Comment by kyo055** [comment]
> with

But I think "delta_p_norm != delta_p_norm" will be optimized by compiler; std::isinfinite() means to that?
