### ISSUE TITLE
Connection to ROS

### ISSUE THREAD

**Issue by TBondat** [koide3/ndt_omp#30]
Hello,

i see in the cmakelist file that the package needs ROS (roscpp) to be built. Is it planned to have a version compatible with ROS2 also?

And could ndt_omp be easilty detached from ros, do you think?

thanks

**Comment by koide3** [comment]
> Is it planned to have a version compatible with ROS2 also?

I wouldn't port it to ROS2 soon. But, any PR is welcome.

> And could ndt_omp be easilty detached from ros, do you think?

The library itself is independent of ROS, and it can easily be detached by removing some catkin-related commands in ```CMakeLists.txt```

**Comment by TBondat** [comment]
Ok, thanks for the feedback!
