### ISSUE TITLE
Support ROS2 build

### ISSUE THREAD

**Issue by KeisukeShima** [koide3/ndt_omp#42]
@koide3 
I ported `ndt_omp` to ROS2 and set up a workflow for CI. <https://github.com/tier4/ndt_omp/pull/5>

I would like to create a pull request to this repository, but before that I would like to discuss how to manage branches.
In our setup, we support both ROS1 and ROS2 builds. Therefore, we can support both in the `master` branch.
However, some repositories (e.g. <https://github.com/ros/diagnostics>) have separate branches like `master` and `ros2-devel`. This simplifies the release process. Which pattern is better for you to manage?

**Comment by KeisukeShima** [comment]
@koide3 Hi, I created a PR to be able to build both ROS1 and ROS2 on the master branch.
If you want to change the branch configuration, please leave a comment. I will recreate the PR.

**Comment by koide3** [comment]
Thanks a lot for your contribution. I prefer supporting both ROS1 and ROS2 on the master branch, and your PR looks fine. I'll review and merge the PR later.
