### ISSUE TITLE
fitness score

### ISSUE THREAD

**Issue by IntelDan** [koide3/ndt_omp#9]
After compare the  fitness score  value in the benchmark, can I get the conclusion, the bigger this value, the better the algorithm are?

**Comment by koide3** [comment]
Hi @IntelDan ,
The smaller fitness score the better (it's the distance between point clouds). In the benchmark, since they all converged, you see almost the same fitness score.

**Comment by IntelDan** [comment]
OK, I know.
Thank you so much!
